### ISSUE TITLE
Feil i ny template 

### ISSUE THREAD

**Issue by geirsandvoll** [PorticoEstate/-Aktiv-Kommune-feil-forslag#12]
Ettersom vi har sagt de kan skru på, så er det noen kritiske ting som ikke er på plass. 

Skulle slå på ny template for Egersund kommune. Den kom på fint, men den klarer ikke å hente data, selv om det ligger masse i Egersund. I tillegg ligger footer til test Bergen. Finner ikke ut hvordan dette kan endres. Når jeg klikker på min side kommer jeg til alle testsøknader til Bergen. Når jeg da igjen klikker på ikonet til Aktiv kommune for å komme tilbake, så kommer jeg til test Bergen instans.

Legger ved noen skjermbilder
![Skjermbilde1](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/67580066/ce1726cc-34fc-4b7c-9f5f-ac096c10f6c1)
![Skjermbilde2](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/67580066/d9171be2-8fac-4121-8f04-d31dfc9d0398)
![Skjermbilde3](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/67580066/24118a78-2ba0-45bc-bfc0-80f7177212b8)
![Skjermbilde4](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/67580066/7e76411f-658b-494c-9bf3-adda418645da)
![Skjermbilde5](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/67580066/17a835f4-179f-4d7e-b0f2-d495daa9b49d)

**Comment by ArildR82** [comment]
@sigurdne lukker du denne når den er løst?
