### ISSUE TITLE
Feil ved Fullførte reservasjoner - duplisering av samme arrangement

### ISSUE THREAD

**Issue by Hildemort** [PorticoEstate/-Aktiv-Kommune-feil-forslag#14]
**Takk for at du melder inn feil**

Feil i #Fullførte reservasjoner"

Beskrivelse av fei:
I listen over "Fullførte reservasjoner" kommer samme arrangement opp to ganger - arrangement blir duplisert.
1. Gå til fullførte reservasjoner.
2. Velg: Hovedbiblioteket
3. Velg: Vis alle 
4. Søk: Oppvekst
5. Da kommer det opp to linjer på ID: 16860  ID 16830 med samme - Reservasjon 4983

Feil: Arrangementet er duplisert på to linjer til fakturering.

**Comment by sigurdne** [comment]
Plan:
Legger inn en oppdatering som fjerner duplikater og legger på et krav om unike poster i tabellen for fakturagrunnlag.
På forhånd sjekkes det (skrives til loggen) - om det er fakturert ut duplikater

**Comment by sigurdne** [comment]
Oppdateringsrutinen er klar, og blir publisert ved neste oppdatering

**Comment by Hildemort** [comment]
> Oppdateringsrutinen er klar, og blir publisert ved neste oppdatering

Så flott, men når vil oppdatering bli gjort, Bare viktig at denne feilen ikke dukker opp igjen.
