### ISSUE TITLE
For direkte booking: Ledige og Opptatte tider må forsvinne fra visning når tidspunkt for starttid er passert ( i dag vises de - dessverre)

### ISSUE THREAD

**Issue by ragnarbu** [PorticoEstate/-Aktiv-Kommune-feil-forslag#16]
Som innbygger,
ønsker jeg ved direkte booking-alternativet kun å få opp (fremtidige) ledige og opptatte leieperioder. Det vil si at ledige og opptatte tider må forsvinne fra listen når start-tidspunktet er passert, eller kanskje 5 minutter før oppstartstid(?)
slik at vi slipper å få passerte tider som et reelt booking-valg i løsningen. Er klokken blitt 11, så er det ingen vits i å kunne bestille timer/tider som startet kl. 9 eller 10 samme dag. Tidspunktet er alt passert, og timene er "ugyldige/uaktuelle" - men de vises likevel i listen over boobare tider i systemet.

**Comment by ragnarbu** [comment]
Det er også ønskelig i enkelte tilfeller  - fra saksbehandlers ståsted - å kunne fjerne leieperioder for direkte booking som er i nær framtid. Dette fordi det ikke skal være mulig for innbygger å bestlile rådgivningstid 5 minutter før eller 24  timer før mulig oppstart("drop-in" aktig). Sakbehandler/rådgiver ønsker å kunne planlegge dagen sin og ha en viss forutsigbarhet. Arbeidsdagen kan bli svært oppstykket dersom det kommer uventede bestillinger rett før.

Hva som defineres som "nær framtid" kan variere, alt fra 1-2 timer til 24 til 72 timer framover i tid (?). For eksempel: Det bør ikke være mulig å bestille tid mandag morgen (etter helg), etter kl. 14 fredagen før. (Igjen ønsker saksbehander/rådgiver å kunne planlegge dette i forkant).

**Comment by sigurdne** [comment]
Gjeld dette ny design, eller gamal - eller begge?
Relater gjerne til "Tubakuba" som case

**Comment by Hildemort** [comment]
Hei Sigurd, for oss gjelder det gammel da det er det vi bruker enn så lenge, men selvfølgelig for ny design også. Ref "Tubakuba"

**Comment by ragnarbu** [comment]
Dette gjeld for både gamal og ny design. Tubakuba ønsker ikkje endring, så vidt eg veit, men eksempel kan vere at tubakuba ikkje skal kunne bestillast på kort varsel - for eksempel er det oppgitt "ledig" i dag, så skal den likevel vere "opptatt" - fordi utleigar ikkje er klar for å handtere eit leigeforhold på kort varsel.  Og så vil det heller ikkje vere råd å hente nøkkel til Tubakuba på laurdagar og sundagar (sidan Innbyggarservice - som levere ut nøkkel - ikkje har opent dei dagane. Men grensa for kor langt fram det ikkje skal kunne bestillast vil variere frå ressurs til ressurs.

**Comment by ragnarbu** [comment]
Her er ei lenke som kan vise problemstillinga: (men for 7.nov er alt greit/opptatt): 
https://site1.aktiv-kommune.no/kristiansand/bookingfrontend/?menuaction=bookingfrontend.uiresource.show&id=323&building_id=121

**Comment by sigurdne** [comment]
1) Har lagt til sjekk på tidsluker som har passert - blir deakivert
2) Har lagt til buffer/frist for booking pr ressurs, slik at en f.eks må booke minst 40 minutt før avtalen starter

**Comment by Hildemort** [comment]
Tilbakemelding 
Kommentar til pkt. 1
Kjempebra.

Kommentar til pkt. 2
Vi kan IKKE ha en buffet på å booke minst 40 minutter før avtalen. Hovedbiblioteket og  Dansesalene på Samsen kulturhus må kunne bookes helt opp til tiden går ut. 
Samtaler med veileder - Byggesak har laget egen daglig rutine at de stenger ledig som de ikke ønsker skal kunne bookes hver morgen.

**Comment by sigurdne** [comment]
Bufferen er konfigurerbar pr ressurs

**Comment by ragnarbu** [comment]
Er det mogleg å få ein titt og ein test på dette?
Eg finn ingenting i tellus/bergen - men leitar kanskje på feil instans, eller i feil skjema (leiter i BOOKING-> BYGG/ANLEGG -> RESSURS

**Comment by Hildemort** [comment]
<img width="309" alt="image" src="https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/145348674/e7ac84b9-5f57-437a-80b0-159a857c7fd9">

Er det her man kan legge til buffer antall minutter ? Vil i så fall tiden bli markert som opptatt ? 

Når blir pkt.1 tidspunkter som passert  - aktivert i AK ?

:)
