### ISSUE TITLE
Feil med kanselleringsepost

### ISSUE THREAD

**Issue by geirsandvoll** [PorticoEstate/-Aktiv-Kommune-feil-forslag#18]
Feilen: 
Systemet sender ut mail om at tid på bygg er kansellert, selv om det er lagt inn at det aldri skal sendes kanselleringsepost fra byggene som er knyttet til hovedaktiviteten. 

Usikker på hva som trigger feilen, men spesielt Sunnfjord og Kristiansand har meldt om disse. 

Slik det skal fungere er at når vi legger inn ID på aktivitet skole f.eks (4), så skal det ikke sendes kanselleringsepost bygg/anlegg med ID 4 sendes ut.

**Comment by sigurdne** [comment]
Konfigurasjon:
![bilde](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/12719970/f4167be0-b836-451d-8a4c-affcf993f9f2)

**Comment by Hildemort** [comment]
Nå har jeg endret fra Nei til Ja i feltet du beskriver. Enig om at dette ikke var helt logisk, men hvis det var det som skulle til så er det helt topp.
