### ISSUE TITLE
Arrangement > SMS varsling til kontaktpersoner der det er overlapping ( fast tildelt tid går ut grunna arrangement) )

### ISSUE THREAD

**Issue by jangunnarhovden** [PorticoEstate/-Aktiv-Kommune-feil-forslag#19]
Hei.
Vi ønsker muligheten til å varsle faste leigetakare via SMS når det opprettes nye arrangement.
I dag kan vi kun varsle via e-post, vi opplever at faste brukere sjeldent får med seg varsling om at deres faste tildelte tid går ut.

under "informer kontaktpersoner" i søknadskjema som saksbehandler bruker har du følgende valg:

"Send melding til registrerte kontaktpersoner av arrangementet"
"send som SMS " ( går kun til søker )
"send melding til registrerte kontaktpersoner der det er overlapping" ( går kun til e-post, her ønsker vi muligheten til å varsle vi sms)
"send e-post til ansvarlig på bygget"

**Comment by sigurdne** [comment]
Kommer i neste oppdatering
