### ISSUE TITLE
Dobbeltbooking på Grupperom på Hovedbiblioteket

### ISSUE THREAD

**Issue by Hildemort** [PorticoEstate/-Aktiv-Kommune-feil-forslag#20]
Hovedbiblioteket har direktebooking uten saksbehandling på sine grupperom.
De har ved enkelte anledninger opplevd at de mottar en NY søknad på leie av grupperom. Dette skal jo ikke være mulig når de har direktebooking.
I dag skjedde det en nytt tilfelle av dette.

Jeg har gått inn i Backend og  sett på begge søknadene.

Søknad #7650 er direkte booket og godkjent uten saksbehandling, men på akkurat samme klokkeslett er det opprettet og sendt inn en søknad til saksbehandling Søkand #7651. 
Jeg har lagt skjermbilde med som vedlegg. 

**Skjermbilder**
Hvis aktuelt, legg til skjermbilder for å forklare problemet ditt.

[Søknad Hovedbiblioteket.docx](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/files/13267077/Soknad.Hovedbiblioteket.docx)

Kan jeg få hjelp til å løse denne ?

**Comment by Hildemort** [comment]
Hei Sigurd, har du fått sett nærmere på denne saken?

**Comment by geirsandvoll** [comment]
Jeg tar denne vekk da den inngår i det issue 34 hvor vi har mer informasjon
