### ISSUE TITLE
Feil i fakturering for Larvik

### ISSUE THREAD

**Issue by ragnarbu** [PorticoEstate/-Aktiv-Kommune-feil-forslag#23]
**Beskriv feilen**
Larvik kommune melder om to faktureringsforhold som må sjekkes og eventuelt korrigeres:

1. Alle tildelinger for **27.september** 2023 kom ut dobbelt i fakturagrunnlaget (Kunder klaget på dobbelt fakturering). Gjelder kun for 27. september - ikke noen datoer før eller etter har fenomenet dukket opp. Det er usikkert på om feilen kan ramme arrangementer for den 27.september. Larvik kommune har INGEN arrangementer den 27.sept. Eksempel: https://site1.aktiv-kommune.no/larvik/index.php?menuaction=booking.uiallocation.show&id=48576&click_history=7c109ba79013ad7eb2ff3b53967b9ccb
Det ligger tilsynelatende bare en tildeling der, men på fakturagrunnlaget dukker det opp to identiske forekomster basert på den ene tildelingen.

2. Det viser seg at i høst har underliggende tildelinger blitt plukket ut i fakturagrunnlag (og blitt fakturert), selv om det er lagt et arrangement OVER tildelingene. Arrangementet er av typen "Stengt" og har Pris = 0. Gjelder for tildelinger i høstferien, og byggene/anleggene "Lardal svømmehall" og "Huldrehallen". 
Dette har ikke skjedd før - og det må være feil at "underliggende" tildelinger blir plukket ut i fakturagrunnlaget. Eksempel: https://site1.aktiv-kommune.no/larvik/index.php?menuaction=booking.uiallocation.show&id=46115&click_history=b71595611139442642955ac3789b00bc

Har også skjermbilder av fenomenene, om det er til hjelp.

**Comment by sigurdne** [comment]
Det ble kjørt en oppdatering den 26/10-2023 som adresserte problemet med duplikater.
