### ISSUE TITLE
Utvide antall tegn i org.navn(gir feilmelding)

### ISSUE THREAD

**Issue by geirsandvoll** [PorticoEstate/-Aktiv-Kommune-feil-forslag#24]
Antall tegn til navn i organisasjonsregisteret har en maks som ikke samsvarer med flere org.navn. 

Under e feilmelding(gir fatal error-meldingen) fra Bærum sin instans: 

SQL: UPDATE bb_organization SET organization_number='983896871',name='ASKER & BÆRUM TAMILSKE FORENING',shortname='ASKER & BÆ',homepage='',phone='N/A',email='',description='N/A',co_address='',street='Postboks 70',zip_code='1314',district='N/A',city='VØYENENGA',active=1,show_in_portal=1,activity_id=1,customer_identifier_type='organization_number',customer_number='',customer_organization_number='983896871',customer_internal=0,in_tax_register=0,customer_ssn='' WHERE id=564

 in File: /porticogit/3024/booking/inc/class.socommon.inc.php

 on Line: 1084

Error: SQLSTATE[22001]: String data, right truncated: 7 ERROR:  value too long for type character varying(11)
 #0	booking_uiorganization->edit() [/porticogit/3024/index.php:131]
#1	booking_boorganization->update(serialized_value = {

**Forventet oppførsel**
Forventet at en skal kunne skrive inn navn av denne lengden og lenger. 

Gjelder egentlig for alle instanser. Ikke stort problem, men skjer der navnene blir av en viss lengde.

**Comment by sigurdne** [comment]
Ser ut til at det er den der "shortname" - hva brukes den til?

**Comment by geirsandvoll** [comment]
Det er vel en forkortelse, brukes vel kanskje på kalender i front + enklere for de enkelte som tildeler tror jeg, egentlig aldri tenkt over det, men Stavanger idrettslag blir S.I.F, letter og skrive sif sikkert

Med vennlig hilsen
Geir Sandvoll Andersen
Rådgiver Innbyggerdialog
Innbygger- og samfunnskontakt
Tlf. 992 95 080

Fra: Sigurd Nes ***@***.***>
Sendt: onsdag 22. november 2023 15:59
Til: PorticoEstate/-Aktiv-Kommune-feil-forslag ***@***.***>
Kopi: Geir Sandvoll Andersen ***@***.***>; Assign ***@***.***>
Emne: Re: [PorticoEstate/-Aktiv-Kommune-feil-forslag] Utvide antall tegn i org.navn(gir feilmelding) (Issue #24)


Ser ut til at det er den der "shortname" - hva brukes den til?

-

**Comment by geirsandvoll** [comment]
Fikk du endret denne? Ikke hørt noe mer, men greit å ha på plass i kode fremover. @sigurdne

**Comment by Hildemort** [comment]
Er denne saken fixet, eller er den lukket og lagt inn i planlagt arbeid @geirsandvoll  ?

**Comment by geirsandvoll** [comment]
Den er lagt i planlagt arbeid :)

**Comment by Hildemort** [comment]
Bare av nyskjerrighet – når kan vi forvente at den er fixet.
Meldte om dette allerede like etter at jeg begynte for to år siden.
Ikke ment negativt, men lurer bare på hvor stor jobb slike ting er og hvor ofte det legges ut oppdatering så sånne endringer.

Hilde😊

Fra: geirsandvoll ***@***.***>
Sendt: torsdag 21. mars 2024 14:41
Til: PorticoEstate/-Aktiv-Kommune-feil-forslag ***@***.***>
Kopi: Hilde Mortensen ***@***.***>; Comment ***@***.***>
Emne: Re: [PorticoEstate/-Aktiv-Kommune-feil-forslag] Utvide antall tegn i org.navn(gir feilmelding) (Issue #24)


Den er lagt i planlagt arbeid :)

**Comment by geirsandvoll** [comment]
Usikker på hvor stor jobben er. Er muligens en ting som sjelden dukker opp og dermed glir sakte ned på listen når nye ting kommer inn. Den ligger i listen over det som skal i sprint, men jeg har ikke konkret dato :)
