### ISSUE TITLE
Feil på kommunelogo - link går ikke til den kommunen som logoen er fra

### ISSUE THREAD

**Issue by IvarEin** [PorticoEstate/-Aktiv-Kommune-feil-forslag#27]
**Takk for at du melder inn feil**

**Viktig at du sjekker om forslaget allerede finnes i listen over innmeldte saker:**
https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/issues 

**Beskriv feilen**
En klar og kortfattet beskrivelse av hva feilen er.

**Gjenskape**
Trinn for å gjenskape atferden:
1. Gå til '...'
2. Klikk på '...'
3. Rull ned til '...'
4. Se feil

**Forventet oppførsel**
En klar og kortfattet beskrivelse av hva du forventet skulle skje.

**Skjermbilder**
Hvis aktuelt, legg til skjermbilder for å forklare problemet ditt.

**Desktop**
  - OS: [f.eks. iOS]
  - Nettleser [f.eks. krom, safari]
  - Versjon [f.eks. 22]

**Mobil**
  - Enhet: [f.eks. iPhone 6]
  - OS: [f.eks. iOS8.1]
  - Nettleser [f.eks. aksjenettleser, safari]
  - Versjon [f.eks. 22]

**Ytterligere kontekst**
Legg til annen kontekst om problemet her.

**Comment by geirsandvoll** [comment]
Ivar Einarsen gjorde meg oppmerksom på at logolenken ikke fungerer i Øygarden, den tar deg kun til ny aktiv kommune side. 

Testet den hos Stavanger, samme der. Har også prøvd å ta vekk http:// i fritekstfeltet der, men får samme resultat

 
![image](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/67580066/c92e3241-b854-46a0-975a-3c948bc2a05d)

**Comment by Hildemort** [comment]
Her i Kristiansand fungerer det 

<img width="521" alt="image" src="https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/145348674/2163fa0b-ac58-461c-abc3-039e8986b1c5">

<img width="799" alt="image" src="https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/145348674/92de8d34-f5de-49d9-b590-47bda34cbb5b">

**Comment by geirsandvoll** [comment]
Da gjelder det ny template. Gammel template så funker linken, ikke på den nye. Takk Hilde

**Comment by sigurdne** [comment]
Har lagt inn url'n
Kommer ved neste oppdaterting
