### ISSUE TITLE
Søker på lag og organisasjoner - Øygarden

### ISSUE THREAD

**Issue by IvarEin** [PorticoEstate/-Aktiv-Kommune-feil-forslag#28]
Når en søker på lag og organisasjoner får en kun opp 10 treff, selv om det er mer en 10 treff. De resterende som ikke vises, kan en heller ikke se, eks. 10 av 25 treff
![Skjermbilde](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/152298771/1c8fe581-6728-4ecc-aa95-d29623d5a7af)

**Comment by Hildemort** [comment]
Gå inn på innstillinger 

![image](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/145348674/4ea505b8-7fed-42dc-8963-d1f8dd9b691e)
Endre antall treff pr. side. 

![image](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/145348674/7c010e57-e944-49a8-b4d1-722809228533)

Håper det løser saken:)

**Comment by IvarEin** [comment]
Hei. Takk for melding, men hos meg er dette på 300 og det endrer ikke noe for min del.

**Comment by IvarEin** [comment]
Ja er nok det, supert å kunne hjelpe hverandre :-) satser på at @geirsandvoll muligens har et svar på denne ?

**Comment by geirsandvoll** [comment]
Denne er i orden
