### ISSUE TITLE
Farge på kalenderen/streker som mangler

### ISSUE THREAD

**Issue by IvarEin** [PorticoEstate/-Aktiv-Kommune-feil-forslag#29]
![image](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/152298771/35f3f9df-426f-4433-b9f7-7d477cffcd33)

Ta bort den grå fargen og legg inn rammer, som viser ledig tider og ikke bare en grå farge, se bilde.

**Comment by geirsandvoll** [comment]
Grå tid er passert tid som ikke skal være mulig å booke. Tar denne bort enn så lenge.
