### ISSUE TITLE
Feil på kalendervisning

### ISSUE THREAD

**Issue by IvarEin** [PorticoEstate/-Aktiv-Kommune-feil-forslag#33]
Ved bruk av kalenderen med flere ressurser, så virker kalenderen på den første ressursen, men velger en en annen ressurs, så blir den ikke oppdatert med annet en en grå flate
Se bilder:

![image](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/152298771/556d8973-914e-43d9-8abe-827947b683ff)

Så velger en neste ressurs
![image](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/152298771/9839a04c-4398-4bf6-8b9d-f50273b1e1f1)

Virker som at kalenderen ikke følger med eller blir oppdatert

**Comment by geirsandvoll** [comment]
Denne er fikset
