### ISSUE TITLE
Feil ved direktebooking uten saksbehandling på Kristiansand Hovedbibliotek

### ISSUE THREAD

**Issue by Hildemort** [PorticoEstate/-Aktiv-Kommune-feil-forslag#34]
**Beskriv feilen**
Biblioteket har grupperom som utleieressurs - disse grupperommene er lalle lagt ut som direktebooking uten saksbehandling. De har ved flere tilfelle oppdaget at det har kommet inn søknad til behandling på disse grupperommene. 
Mener jeg har snakket med Sigurd om dette tidligere, men nå når det dukker opp igjen registrerer jeg det som en sak.

Har lagt ved en skjermdump her som viser at dette skjedde i går, og også to tidligere tilfeller. 
Kan vi sette av tid til å finne feilen? 
Selvfølgelig frustrerende for biblioteket. 

<img width="628" alt="image" src="https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/145348674/2d5b159b-2709-463a-a6e7-05f65a5ee7a7">

**Comment by geirsandvoll** [comment]
Trenger vi kanskje en dump her Sigurd, eller er det noe som man finner utenom?

**Comment by Hildemort** [comment]
Hei, Jeg håper vi kan prioritere å finne løsningen på dette problemet. Fikk melding fra biblioteket om at det samme hadde skjedd i går. Er det mulig å få satt av tid til å se på dette? Trenger dere mer informasjon. 
Dette er et problem de har hatt over lang tid, så hadde vært veldig bra å komme til bunns i dette, og få rettet feilen.

<img width="584" alt="image" src="https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/145348674/76bae523-3a4b-4435-ab49-09410a74ffce">

**Comment by Hildemort** [comment]
Ny feil av samme slag som tidligere meldt. Nå har Ragnar og meg sett litt nærmere på det. Det viser at det opprettes en ekstra søknad i samme øyeblikk som direktebooking. 


<img width="736" alt="image" src="https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/145348674/c59cec38-6335-4673-ab2f-00c47ac786d9">

**Comment by geirsandvoll** [comment]
Den forrige du meldte inn var en variant med to unike søkere som søkte samtidig. Her ble den ene godkjent, og den andre ble lagt som ny søknad. 

Men den dupliserer ikke alle søknader på grupperommet?

**Comment by geirsandvoll** [comment]
Glemte å legge ved skjermbildene, mente ikke det var alene årsaken, er nok mer kompleks ja. 

Men forrige uke så jeg på den søknads ID 9464 som ligger inne som ny søknad, for tidspunktet 16. januar klokken 16. Når jeg sjekket kalenderen på den dagen så lå det et godkjent arrangement der, med søknads ID 9472. Disse to søknadene ble opprettet på samme tidspunkt(to unike), ifølge informasjonen jeg fant. La ved to skjermbilder under. 

Men nå har vi mye god dokumentasjon på det som slår ut feil. @sigurdne Har du det du trenger?

![Skjermbilde 2024-01-23 090136](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/67580066/897d13ef-1f96-4840-9bcf-989272350193)
![Skjermbilde 2024-01-23 090213](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/67580066/a52eb9bb-ca07-4f37-91eb-264392253942)

**Comment by Hildemort** [comment]
Bare å ta kontakt med meg også hvis spørsmål @sigurdne. Håper du kan løse denne floken :)

**Comment by Hildemort** [comment]
De fortsetter å motta dobbel søknader
<img width="785" alt="image" src="https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/145348674/3c65273f-a3a3-468d-b2e6-c88ec27cd831">

**Comment by geirsandvoll** [comment]
Da lukkes denne enn så lenge. Satser på at feilen nå er løst. Om ikke tar vi den opp igjen.

**Comment by Hildemort** [comment]
Hei Sigurd, denne saken må dessverre åpnes igjen. 

Denne søknaden kom inn i dag.

<img width="773" alt="image" src="https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/145348674/2d811bfd-7629-4068-89cc-3f9812bbc6cc">

**Comment by Hildemort** [comment]
Det fortsetter å komme duplikat/dobbelt søknad på Hovedbiblioteket:
Feilen er den samme. 
En søknad godkjennes automatisk som direktebooking skal, og den andre kommer inn som NY søknad som krever behandling.


<img width="775" alt="image" src="https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/145348674/20113b94-fa07-4aad-a170-368a5a4c3bcd">

**Comment by Hildemort** [comment]
Har du hatt muligheten til å se mer på dette problemet @sigurdne ?

**Comment by Hildemort** [comment]
Hei Sigurd og Geir, 

I dag opplever jeg at samme feil skjer på Byggesak.

<img width="775" alt="image" src="https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/145348674/d7e9a6e6-c0a5-4492-b868-79b7e56c1898">

Det hadde vært veldig greit om du har mulighet til å prioritere å se på denne saken Sigurd. Det begynner å bli lenge siden den ble rapportert første gang. Håper du har mulighet til det :)

**Comment by geirsandvoll** [comment]
Hei @Hildemort Prøver å lukke den igjen. Nå har det gått en god stund uten nye henvendelser på denne.

**Comment by Hildemort** [comment]
[like]  Hilde Mortensen reacted to your message:
________________________________
