### ISSUE TITLE
Mobilvisning av Aktiv kommune

### ISSUE THREAD

**Issue by Hildemort** [PorticoEstate/-Aktiv-Kommune-feil-forslag#36]
Hei og godt nytt år.
Starter det nye ønske med et forbedringsforslag.

For de som jobber i drift, er mye på farten og trenger informasjon fra Aktiv Kommune er det veldig praktisk å kunne logge seg inn på Back-end fra sin mobiltelefon for å finne informasjon om arrangement, kalender osv. 

Det er mulig i dag, men Backend er ikke helt mobiltilpasset. 
Eksempel:
Arrangement: her får man kun opp de 6 første kolonnene, og det her heller ikke mulig å flytte bildet mot venstre for å se resten av kolonnene.

**Comment by ArildR82** [comment]
Takker for dette inspillet @Hildemort  vet det er lenge siden du har meldt det inn. Jeg er ganske sikker på at det nye administrasjonsgrensesnittet vil være brukbart på mobil også, kanskje ikke alle visninger men de mest brukte sidene. Vi vil ikke gjøre noe med nåværende administrasjonsgrensenitt med tanke på mobilvennlighet, det blir for mye jobb og en kortvarig glede.  Lukker dette inspillet da det ble lagt inn i backlogen i januar.
