### ISSUE TITLE
Språkvelger i ny template fungerer ikke

### ISSUE THREAD

**Issue by ragnarbu** [PorticoEstate/-Aktiv-Kommune-feil-forslag#39]
På ny landingsside er det mulighet for å velge språk, pr i dag 
Norsk  eller
Engelsk

Når vi trykker på Engelsk, så bytter flagget til det engelske, men språket er like fullt NORSK.

**Comment by geirsandvoll** [comment]
Vi starter språklistene når vi er ferdig med front, tester AI på disse også.

**Comment by geirsandvoll** [comment]
Sigurd har lagt inn felt for bokmål, nynorsk og engelsk. Det fordrer at saksbehandler må manuelt legge inn en engelsk, bokmål og nynorsk variant av beskrivelsen.
