### ISSUE TITLE
Feil i kalendervisning - ny template

### ISSUE THREAD

**Issue by ragnarbu** [PorticoEstate/-Aktiv-Kommune-feil-forslag#40]
For hvert månedskifte viser kalenderen feil. Selv om tidsrommet er reservert/opptatt, så er det ingenting som vises på formiddagen den 1.februar, og 1.mars.

Se vedlagt skjermbilde:

Testet på FIREFOX nettleser (Desktop/PC)
.

Lenke:
https://site1.aktiv-kommune.no/bergen/bookingfrontend/#booking

og velg Tubakuba
[Feil nr 2 i kalendervisning.docx](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/files/13946640/Feil.nr.2.i.kalendervisning.docx)

**Comment by ArildR82** [comment]
@ragnarbu  denne er også fikset
