### ISSUE TITLE
Ny template åpner ny utleieperiode alt for tidlig!

### ISSUE THREAD

**Issue by ragnarbu** [PorticoEstate/-Aktiv-Kommune-feil-forslag#41]
I ny template åpnes ny utleieperiode alt for tidlig - og for langt fram i tid.
Tubakuba og Egget skal åpne april måned for booking den 1.februar, men er alt åpen for booking - i ny template (gamme template er ok)

Se skjermbilder - vedlagt.

**Forventet oppførsel**
Tubakuba og Egget skal nå i januar kun leie ut datoer fram til 1.april.
April skal ikke åpnes for utleie før 1.februar.
Og juni skal ikke åpnes for utleie  før 1.april.!

**Desktop**

  - Nettleser FIREFOX
- versjon 121.0.1
[Kritisk feil - leieperiode åpner for tidlig.docx](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/files/13946781/Kritisk.feil.-.leieperiode.apner.for.tidlig.docx)

**Comment by Promises** [comment]
Sjekker opp i det

**Comment by Promises** [comment]
Dette er nå fikset
