### ISSUE TITLE
Manglar i ny kalendervisning (ny template) , delar av funksjonaliteten fungerer i gamal template/kalender.

### ISSUE THREAD

**Issue by ragnarbu** [PorticoEstate/-Aktiv-Kommune-feil-forslag#42]
Ny kalender ( i ny template) har manglar i informasjonen i popup-vinduet som dukkar opp om brukar trykker på enkeltarrangement/enkeltildeling.

Og kalenderen ser litt snål ut her og der, sjå vedlegg.

Testa på Firefox-nettlesar.
[Manglar i kalendervisning- ny template.docx](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/files/13974217/Manglar.i.kalendervisning-.ny.template.docx)

**Comment by ArildR82** [comment]
@ragnarbu denne skal være i orden, lukker issuet
