### ISSUE TITLE
Feil i kalender (ny template) 

### ISSUE THREAD

**Issue by ragnarbu** [PorticoEstate/-Aktiv-Kommune-feil-forslag#43]
Det er feil i kalendervisning for "Byggesak..." i Kristiansand kommune

Sjå vedlegg
[Feil nr 3 i kalendervisning - Kristiansand.docx](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/files/13989752/Feil.nr.3.i.kalendervisning.-.Kristiansand.docx)

Testa i Firefox - på desktop

**Comment by ArildR82** [comment]
Har testet denne nå @ragnarbu , det ser bra ut. Kan du også sjekke, endre status til ferdig dersom den er ok.

**Comment by geirsandvoll** [comment]
Denne er løst. Developemode er også skrudd på for Kristiansand.
