### ISSUE TITLE
Forslag til annen rekkefølge i utfylling av søknadsskjema - ny template

### ISSUE THREAD

**Issue by ragnarbu** [PorticoEstate/-Aktiv-Kommune-feil-forslag#53]
Når jeg som bruker ønsker å fylle ut en søknad, så er dagens versjon den jeg kan fylle ut "leieobjekt" , men la være å fylle ut "leieperiode", før jeg "går videre i utfyllingen av søknadskjemaet.
Etter en stund (side 2), vil jeg da få en - litt knapp(?)- feilmelding om å fylle ut "Fra" og "Til"-feltet. 
Denne meldingen er bare delvis rett- man må OGSÅ fylle ut DATO og trykke LEGG til leieperiode.

Se vedlegg.
[Feil og mangler i søknadskjema - ny template 25 april 2024.docx](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/files/15106974/Feil.og.mangler.i.soknadskjema.-.ny.template.25.april.2024.docx)

**Comment by geirsandvoll** [comment]
Det bør den absolutt gi beskjed om før en kan gå videre. Godt beskrevet @ragnarbu . Mulig noe som kan justerer med et kriterie. 
@ArildR82

**Comment by ArildR82** [comment]
Jeg legger denne inn i juni sprinten, takk @ragnarbu !

**Comment by ArildR82** [comment]
Lukker denne da den er lagt inn i sprint
