### ISSUE TITLE
Fatal feil ved sending av melding ved overlappende arrangement

### ISSUE THREAD

**Issue by anenola** [PorticoEstate/-Aktiv-Kommune-feil-forslag#57]
Jeg har booket et arrangement over tildelinger. Når jeg skal sende melding til kontaktpersoner der det er overlappende arrangementer får jeg opp siden med fatal feil, og melding sendes ikke ut.

**Gjenskape**
Trinn for å gjenskape atferden:
1. Opprett arrangement
2. Skriv tekst du ønsker å sende til kontaktpersoner der det er overlappende arrangement.
3. Hak av for at melding skal sendes til kontaktperson der det er overlappende arrangement.
4. Trykk godkjenn
5. Fatal feil kommer opp.

**Forventet oppførsel**
E-post sendes til personer der det er overlappende arrangement.

**Skjermbilder**
Fra feilmeldingsloggen: ![image](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/144990010/f62375d7-2467-437f-a105-1a5ba1e62477)

**Desktop**
  - OS: windows
  - Nettleser chrome
  - Versjon ?

**Comment by anenola** [comment]
@geirsandvoll Jeg trodde jeg definerte denne som kritisk feil. Men tagger deg i hvert fall, så du får beskjed.

**Comment by geirsandvoll** [comment]
@anenola Det ser ut som SMS ikke er satt opp hos dere. Ser i feilmeldingsloggen at det er createObject(sms) som feiler ettersom modulen ikke er satt opp. Jeg kan sette det opp om ønskelig? Tror jeg skal få tid i morgen ettermiddag. Enn så lenge ligger den kosten her hos oss, det gjelder alle kommunene som har SMS satt opp.

**Comment by anenola** [comment]
@geirsandvoll  Jeg forsøker ikke å sende sms. Jeg gjør slik vi tidligere har gjort det for å sende epost. I bildet under ser du hva jeg har fylt ut før jeg trykker godkjenn.

Vi ønsker foreløpig ikke sms.

![image](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/144990010/2711cc59-8642-401c-ab9d-7485f69acfd2)

**Comment by geirsandvoll** [comment]
Ok. @sigurdne kan du ta en nærmere titt på den? Sender en epost i tillegg på den.

**Comment by anenola** [comment]
Jeg forsøkte på et testbygg nå, hvor jeg selv er kontaktperson for tildelingen. Og jeg fikk epost selv om jeg fikk fatal feil opp på skjermbildet da jeg trykket godkjenn.

Betyr det at den prøver å sende SMS i tillegg til epost?

**Comment by sigurdne** [comment]
Ja, det stemmer.
Prøver å sende  både sms og epost til kontakter ved overlapp.

**Comment by anenola** [comment]
Det er vel dumt at den prøver på når vi ikke har satt opp sms. Dette er forvirrende for saksbehandler, da man tror at epost om overlappende booking ikke er sendt ut grunnet fatal feil.

**Comment by sigurdne** [comment]
Har oppdatert koden til å ta hensyn til modul-status.
Sett 'SMS' til 'Deaktivert'

![bilde](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/12719970/c9c776e4-e2b1-4ebc-9b15-527a17b06aff)

**Comment by geirsandvoll** [comment]
@anenola Bærum er oppdatert. Kunne du testet og gitt en tilbakemelding på om det går fint?

**Comment by anenola** [comment]
Jeg fikk fortsatt melding om fatal feil. Epost sendes fortsatt ut til kontaktperson på overlappende tildeling. 

![image](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/144990010/7297d5f6-f43a-48c8-b318-2e5b47064e65)

**Comment by geirsandvoll** [comment]
@anenola Den var ikke satt til deaktivert. Jeg har logget på Bærum og deaktivert sms applikasjonen. Prøver du igjen?

**Comment by anenola** [comment]
Takk for hjelp med riktige innstillinger.

Nå fikk jeg ikke opp beskjed om fatal feil, og meldinga legger seg i loggen på arrangementet. Så da fungerer det. Tusen takk for hjelp.

**Comment by geirsandvoll** [comment]
Supert :) Lukker denne da så får den heller tas tak i om problemet skulle oppstå igjen.
