### ISSUE TITLE
Feil på frontend i ny versjon

### ISSUE THREAD

**Issue by IvarEin** [PorticoEstate/-Aktiv-Kommune-feil-forslag#59]
I ny versjon av front end viser ikke tildelinger, bare arrangement. Tildelinger viser med grått felt, med kun tildelingsnummer og ikke hva som er der

![image](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/152298771/af4b2bf5-9627-4036-880a-b47301a30b86)

Og ved stengt over lengre periode vises dette...

![image](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/152298771/605a6a7b-8972-42f7-bf16-bf5c2383fc2b)

**Comment by ArildR82** [comment]
Takk @IvarEin , her er det noe som ikke er helt som det skal. Melder fra om dette til utvikler ASAP. 

@geirsandvoll
