### ISSUE TITLE
Fakturering UBW utvikling Bærum kommune

### ISSUE THREAD

**Issue by anenola** [PorticoEstate/-Aktiv-Kommune-feil-forslag#6]
Er det mulig å få forskjellig org.nr. i text3 og text4 på fakturafila? At text 3 hentes fra org.nr under organisasjon/bedrift og text 4 hentes fra org.nr under fakturainformasjon under organisasjoner. 

Er det også mulig i UBW grunnlagsfila å vise om det skal faktureres med eller uten MVA på varelinjene? Er det et felt som kan brukes til dette?

**Comment by ArildR82** [comment]
Sjekker opp i dette @anenola

**Comment by sigurdne** [comment]
Har lagt ut ny kode for test:
Under "Konteringsdimensjoner" - merk av for differensiering mellom organisasjon og betaler

![bilde](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/12719970/c8e12b63-a2a8-4da1-818c-f483c185185f)

**Comment by anenola** [comment]
Dette fungerte ikke helt enda. 

Det samme org.nr. ligger to steder i grunnlagsfila selv om org. er satt opp med to forskjellige org.nr. Det havner i text 4 og "ekst.ref". Referansen til org. kom ikke med i fila. Vedlagt ligger fila. 

[export_external_170.txt](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/files/12711960/export_external_170.txt)

**Comment by ArildR82** [comment]
Hei @anenola, @sigurdne  ser på dette når han får anledning.

**Comment by anenola** [comment]
Jeg fikk tilbakemelding etter ny test:

Problemet er at det har skjedd en forskyvning i filens øverste linje slik at FK kommer i feltet for bilagsreferanse, dette er tall felt så da feiler det.  Dere bør melde dette tilbake til forsystemet slik at de får korrigert det.

Får vi justert dette?

Har dere også fått sett på muligheten for å skille type mva i grunnlagsfila?

**Comment by sigurdne** [comment]
Avslutter saken etter siste justeringer og testing
