### ISSUE TITLE
Juridiske betingelser laster ikke

### ISSUE THREAD

**Issue by edudppaz** [PorticoEstate/-Aktiv-Kommune-feil-forslag#69]
**Takk for at du melder inn feil**

**Viktig at du sjekker om forslaget allerede finnes i listen over innmeldte saker:**
https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/issues 

**Beskriv feilen**
Det er ikke mulig å godkjenne Juridiske betingelser

**Gjenskape**
Trinn for å gjenskape atferden:
1. Prøv å sende søknad til en bydelhus
2. Kan ikke gå videre pga Juridiske betingelser et ikke godtatt

**Forventet oppførsel**
Det er mulig å godkjenne betingelser.

**Skjermbilder**
![Screenshot 2024-08-09 at 12 15 23](https://github.com/user-attachments/assets/f0fd230e-f945-49f3-b424-ac8809baba4f)

**Desktop**
  - OS: MacOS
  - Nettleser: Prøvd Chrome, Firefox, Safari og Firefox på Android
  - Versjon 

**Mobil**
  - Enhet: Android
  - OS: -
  - Nettleser : Firefox og chrome
  - Versjon [f.eks. 22]

**Ytterligere kontekst**
Legg til annen kontekst om problemet her.

**Comment by geirsandvoll** [comment]
Bygg/anlegg som det er lastet opp et juridisk dokument får denne feilen og man kommer ikke videre.

**Comment by Promises** [comment]
@geirsandvoll  @edudppaz Gjelder dette ein spesifikk instanse? tester her med android firefox hos Bergen, og det laster riktig

Kan gjerne teste videre

**Comment by geirsandvoll** [comment]
Kun Stavanger, som har nyeste variant.

Stavanger(1103): mandag 05.aug. 13:13 - Git Branch:Version-2_0-branch

Med vennlig hilsen
Geir Sandvoll Andersen
Rådgiver Innbyggerdialog
Innbygger- og samfunnskontakt
Tlf. 992 95 080

Fra: Henning Berge ***@***.***>
Sendt: mandag 12. august 2024 12:49
Til: PorticoEstate/-Aktiv-Kommune-feil-forslag ***@***.***>
Kopi: Geir Sandvoll Andersen ***@***.***>; Mention ***@***.***>
Emne: Re: [PorticoEstate/-Aktiv-Kommune-feil-forslag] Juridiske betingelser laster ikke (Issue #69)


@geirsandvoll<https://github.com/geirsandvoll> @edudppaz<https://github.com/edudppaz> Gjelder dette ein spesifikk instanse? tester her med android firefox hos Bergen, og det laster riktig

Kan gjerne teste videre

-

**Comment by edudppaz** [comment]
> @geirsandvoll @edudppaz Gjelder dette ein spesifikk instanse? tester her med android firefox hos Bergen, og det laster riktig
> 
> Kan gjerne teste videre

Tror det gjelder alle instanser i stavanger med Juridiske betingelser men kan er ikke sikkert. Har prøvd akkurat nå med Tjensvoll Bydelhus /  Ungdomslokale i Stavanger.

**Comment by geirsandvoll** [comment]
Det gjelder kun Stavanger, og kun bygg som ikke har lagt ved juridisk dokument 😊

Med vennlig hilsen
Geir Sandvoll Andersen
Rådgiver Innbyggerdialog
Innbygger- og samfunnskontakt
Tlf. 992 95 080

Fra: Eduardo Pozo ***@***.***>
Sendt: mandag 12. august 2024 12:55
Til: PorticoEstate/-Aktiv-Kommune-feil-forslag ***@***.***>
Kopi: Geir Sandvoll Andersen ***@***.***>; Mention ***@***.***>
Emne: Re: [PorticoEstate/-Aktiv-Kommune-feil-forslag] Juridiske betingelser laster ikke (Issue #69)


@geirsandvoll<https://github.com/geirsandvoll> @edudppaz<https://github.com/edudppaz> Gjelder dette ein spesifikk instanse? tester her med android firefox hos Bergen, og det laster riktig

Kan gjerne teste videre

Tror det gjelder alle instanser i stavanger med Juridiske betingelser men kan er ikke sikkert. Har prøvd akkurat nå med Tjensvoll Bydelhus / Ungdomslokale i Stavanger.

**Comment by Promises** [comment]
Kan det mangle Juridiske betingelser? Ser ut som det blir ikkje godkjent om betingelser mangler.

Fikser opp i det

**Comment by Promises** [comment]
@geirsandvoll då er dette fikset i master

**Comment by geirsandvoll** [comment]
Da har jeg testet og det er løst i produksjon. Avslutter dermed denne.

**Comment by edudppaz** [comment]
Funker nå, takk.
Til info, nå det kommer en tekts unner Juridiske Bt..:

`Missing translation for [bookingfrontend][no_documents_to_accept]`
