### ISSUE TITLE
Leie lokale i Aktiv Kommune, Stavanger

### ISSUE THREAD

**Issue by johanlrdahl** [PorticoEstate/-Aktiv-Kommune-feil-forslag#72]
**Beskriv feilen**
Det virker helt umulig å søke på noe som helst når man prøver å leie et lokale i aktiv kommune (i Stavanger)

**Gjenskape**
Trinn for å gjenskape atferden:
1. Gå til '(https://site1.aktiv-kommune.no/stavanger/bookingfrontend/#booking)'
2. Prøv å filtrer på noe som helst for å "Leie"
3. Det kommer ingen valg opp uansett filter, og det er ingen søke-knapp

**Forventet oppførsel**
Enten at mulige lokaler kommer opp automatisk, eller at det finnes en "søk"-knapp man kan benytte

**Skjermbilder**
<img width="1380" alt="image" src="https://github.com/user-attachments/assets/49a0e5c8-b1a9-4e6e-b6ac-772bb540c55c">

**Desktop**
  - OS: Mac OS X, Windows 11
  - Nettleser Chrome og Safari
  - Versjon: Chrome 128.0.6613.119, Safari 17.6 på Mac

**Mobil**
  - Enhet: iPhone 14 Pro
  - OS: iOS
  - Nettleser: Safari
  - Versjon: iOS 17.6.1

**Ytterligere kontekst**
N/A

**Comment by ArildR82** [comment]
Hei @johanlrdahl takk for tilbakemelding. 

Jeg testet ut det samme søket og jeg skjønner hva du mener. Det virker som at det ikke skjer noe. Men det som skjer er at det ikke er noen lokaler som er blitt tagget med "korps" og som er mulig å leie på den datoen du har valgt.  Det burde kommet tydelig frem at ditt søk ikke ga noen søkeresultater. Jeg legger dette som en utviklingsoppgave. 

Takk for innspill!

**Comment by johanlrdahl** [comment]
Takk. Da lukker jeg denne :)
