### ISSUE TITLE
Tilknytta element i søknad

### ISSUE THREAD

**Issue by HegeAS** [PorticoEstate/-Aktiv-Kommune-feil-forslag#73]
Når søker har sendt inn søknad om ønsket leietid på vegne av sin gruppe og saksbehandler gir en interntildeling blir både tildelingen og interntildelingen (booking) knyttet til element i søknad. Både tildeling og interntildelingen blir oppgitt med pris og søker tror det blir dobbelt så dyrt å leie.

Som en saksbehandler
ønsker jeg at kun interntildelingen med pris skal oppgis i søknaden
slik at det vises korrekt pris til søker.
![Tilknytta element søknad](https://github.com/user-attachments/assets/d03c3bef-032b-4b5c-824a-6ea4d08e3fa4)

**Comment by ArildR82** [comment]
Takk @HegeAS, jeg legger denne i utviklingskøen. Og merker den som lukket her.
