### ISSUE TITLE
Kunne endre på : Max antall deltakere 

### ISSUE THREAD

**Issue by Hildemort** [PorticoEstate/-Aktiv-Kommune-feil-forslag#8]
Får ikke satt "Max antall deltakere" lik null når det er lagt inn en verdi i dette feltet. 

På ressursnivå er det mulig å legge inn : Max antall deltakere.

Tror dette er en funksjonalitet som ble lagt inn under korona for å kunne legge inn et max antall og at søker registrerte seg på en liste. 

På Samsen kulturhus er dret lagt inn verdi på ressurser i dette feltet. Da det ble lagt inn trodde de det hadde sammenheng med reell kapasitet i det enkelte lokale.
Vi ønsker å fjerne denne verdien, men har ikke klart det. Legger jeg inn verdien 0 skjer det ingen ting. Fikk tips om å legge inn -1, men det hjalp heller ikke. 
Trenger å kunne få fjernet verdiene i dette feltet. 
Har lagt ved bilde som beskriver dette.
 
[Max antall deltakere.docx](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/files/12647482/Max.antall.deltakere.docx)

**Comment by sigurdne** [comment]
Da er det lagt inn en justering:
"-1" vil virke som begrensning ikke angitt, dersom en vil beholde historikk
Og en kan fjerne en oppføring ved å angi dato (for oppføring som skal fjernes) - og tom verdi for antall



![Image](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/assets/12719970/25f96eaa-013a-4db1-8627-6b264fcb32e6)

**Comment by sigurdne** [comment]
Server må oppdateres først
(slettingen vil fungere)

**Comment by Hildemort** [comment]
Beklager, men jeg forstår ikke helt hva du mener med : slettingen vil fungere?

**Comment by Hildemort** [comment]
God morgen Arild, bare et spørsmål til denne saken. Den er lukket, men ikke fixet. Kan du se på dette er du snill?

**Comment by sigurdne** [comment]
Fikset
