### ISSUE TITLE
Søker får fatal feil når ved innsending av søknad 

### ISSUE THREAD

**Issue by Hildemort** [PorticoEstate/-Aktiv-Kommune-feil-forslag#87]
**Beskriv feilen**
Søker får fatal feil ved innsending av søknad på Samsen kulturhus. Bygg, ressurs, dato og tid velges, søknadsskjema fylles ut, juridiske betingelser aksepteres. Søker går videre og logger seg inn med BankID, når hun skal gå videre for å velge faktura-informasjon får hun Fatal feil.

Sigurd ble kontaktet av @geirsandvoll i går. Begge så feilmelding i logg over Fatal feil. Sigurd sa at server måtte restartes. Jeg fikk ikke endelig bekreftet at server ble restartet i går. 

Søker forsøkte uansett i går kveld litt før 20:00 og sende inn ny søknad. Se informasjon fra søker nedenfor:

Her er informasjon fra søker.

Jeg har prøvd igjen fra 2 forskjellige PCer, og 3 forskjellige nettlesere (firefox, chrome og edge), men fikk samme feil.

**Comment by Hildemort** [comment]
Da har søker igjen forsøkt å sende inn en søknad. Hun får samme feilmelding. Fatal feil.
Hun skriver følgende:

Jeg lurer imidlertid på om det er noe galt med min bruker-ID i Aktiv kommune. Er jeg blokkert?
Jeg ønsker å få avklart dette, da jeg har en rolle i flere foreninger og tidligere har leid lokaler både ved Samsen kultursenter og Tinnheia fritidssenter. Jeg planlegger også å gjøre dette i fremtiden.

Hun heter : Rawda Assefa Abebe

Kan det være tilfelle @geirsandvoll @ArildR82 ?

**Comment by Hildemort** [comment]
Søker har nå også forsøkt annet bygg. Se her hva hun skriver:

Jeg fikk fortsatt feilmelding når jeg testet nettopp å sende inn søknad. "Fatal Error".

**Comment by Hildemort** [comment]
Hei, 
Jeg skulle gjerne gitt tilbakemelding til søker som har problemer. Har dere fått sett nærmere på dette @ArildR82 @geirsandvoll ?

**Comment by ArildR82** [comment]
Hei @Hildemort Kan du be henne ta kontakt med Geir på e-post slik at han kan se på når hun forsøker å bestille?

Gjelder det forresten andre brukere eller bare den ene brukeren?

**Comment by Hildemort** [comment]
Hei @ArildR82 
Da har jeg sendt mail til bruker og bedt henne avtalt med Geir.
Jeg har ikke hørt om andre brukere som har møtt på samme problem.

**Comment by geirsandvoll** [comment]
Fikk mail om at hun fikk tilsendt nå. Jeg lukker den enn så lenge, så får vi ta den opp igjen om det dukker opp. Har ikke hatt andre tilfeller på dette.
