### ISSUE TITLE
Kontaktinformasjon/bookingansvarlig hentes ikke med når arrangement opprettes

### ISSUE THREAD

**Issue by Hildemort** [PorticoEstate/-Aktiv-Kommune-feil-forslag#9]
Når saksbehandler skal opprette ett arrangement og velge fakturainformasjon hentes ikke kontaktinformasjon som er lagt inn fra organisasjon.
Se vedlagte fil. 
[Opprette arrangement - kontaktinfo hentes ikke med i arrangementet.docx](https://github.com/PorticoEstate/-Aktiv-Kommune-feil-forslag/files/12657126/Opprette.arrangement.-.kontaktinfo.hentes.ikke.med.i.arrangementet.docx)

**Comment by sigurdne** [comment]
Fikset

**Comment by Hildemort** [comment]
Har du fixet dette så det blir rettet ved en ny oppdatering av kode?? og når skjer det. Bare så jeg forstår hvordan dette systemet fungerer.
